services:
    adminer:
        container_name: adminer
        image: adminer
        ports:
            - 8080:8080
    mysql:
        build: ./mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=laravel
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - 8000:80
        volumes:
            - ./project/laravel:/var/www/html
    node.js:
        build: ./node.js
        container_name: node.js
        command: >
            sh -c "npm i && npm update && npm fund && npm audit fix && npm start"
        ports:
            - 4200:4200
        volumes:
            - ./project/node.js:/home/node/node.js-project
    php-fpm:
        build: ./php-fpm
        command: >
            sh -c "composer install && chmod 777 -R ./storage && docker-php-entrypoint php-fpm"
        container_name: php-fpm
        volumes:
            - ./project/laravel:/var/www/html
version: "3"