services:
    adminer:
        container_name: adminer
        image: adminer
        ports:
            - 8080:8080
    mysql:
        build: ./mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=laravel
    nginx:
        build: ./nginx
        container_name: nginx
        depends_on:
            - php-fpm
        ports:
            - 8000:80
        volumes:
            - ./project:/var/www/html
    node.js:
        build: ./node.js
        command: >
            sh -c "npm i && npm update && npm audit fix && npm run hot"
        container_name: node.js
        ports:
            - 8081:8081
        volumes:
            - ./project:/home/node.js/node.js-project
    php-fpm:
        build: ./php-fpm
        command: >
            sh -c "composer install && composer update && docker-php-entrypoint php-fpm"
        #command: >
        #    sh -c "composer install && composer update && chmod 777 -R ./storage && chmod 777 -R ./vendor && docker-php-entrypoint php-fpm"
        container_name: php-fpm
        volumes:
            - ./project:/var/www/html
version: "3"